---
- hosts: all
  become: yes
  tasks:
    - name: Set timezone
      command: timedatectl set-timezone Asia/Tbilisi

    - name: Update and install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      loop:
        - build-essential
        - net-tools
        - curl
        - git
        - software-properties-common
        - chrony

    - name: Allow NTP traffic
      ufw:
        rule: allow
        port: '123'
        proto: udp

    - name: Update chrony configuration to allow NTP traffic from subnet
      lineinfile:
        path: /etc/chrony/chrony.conf
        line: 'allow 192.168.56.0/24'

    - name: Restart chrony service
      service:
        name: chrony
        state: restarted